#!/bin/ksh

tf=Config.mk
cc=cc

[ "`uname -m`" = 'i86pc' ] && cc=gcc

print "" > ${tf}

ostype=`uname -s`

case $ostype in

	SunOS)
		print 'TARGETS=$(OBJS)'					>> ${tf}
		print '  CC='$cc' $(INCLUDES) -O'			>> ${tf}

	;;

	HP-UX)
		print 'TARGETS=$(OBJS)'					>> ${tf}
		print '  CC='$cc' $(INCLUDES) -O +Z'			>> ${tf}

	;;
esac

#END
