#!/bin/sh
#
# @(#)setup-cgi	1.1 05/15/97
#
src=$1
if [ ! -d "$src" ]; then
	echo Usage: $0 npaswd-source-directory
	exit 1
fi

echo Setting up npasswd distribution facility in `pwd`
umask 02

EXEC="sh -x"

case `pwd` in
	*public_html)	;;
	*)	echo Not in public_html directory
		exit 1
		;;
esac

(
	cd cgi-bin || exit 1
	echo DIRECTORY `pwd`
	for f in register download admin; do
		echo ln -s npasswd-request.cgi npasswd-$f.cgi | $EXEC
	done
	chmod 0755 npasswd-request.cgi
)

(
	cd npasswd/v2.0/ || exit 1
	mkdir doc
	(
	cd doc || exit 1
	echo DIRECTORY `pwd`

	for f in `awk '{ print $1 }' $src/MANIFEST | grep "^doc/" | grep -v '.SH$'`; do
		echo cp $src/$f . | $EXEC
	done
	)
	echo DIRECTORY `pwd`
	echo cp $src/npasswd-*tar.Z . | $EXEC
	echo chmod 0444 npasswd-*.tar.Z | $EXEC

	h=`hostname`
	u=`logname`
	rm -f index.RAW
	mv index.html index.RAW
	sed -e \
	     "s@__REQUEST__@http://$h/cgi-bin/cgiwrap/$u/npasswd-request.cgi@"\
	     index.RAW  > index.html
	echo Fixed reference in index.html
)
#
# End setup-cgi
