all::
	@echo "1. Move Makefile.dist to Makefile."
	@echo "2. Edit Makefile to uncomment the 'all' target,"
	@echo "   change the desired target to 'npasswd',"
	@echo "   and select the build options."

