#!/bin/sh
flags=""
case "$@" in
*--*)
	for arg
	do
		shift
		case "$arg" in
		--) break;;
		*) flags="$flags $arg";;
		esac
	done;;
esac
for srcfile
do
	/usr/ucb/cpp -M -I. -D__LANGUAGE_C__ -D_NO_PROTO -DOS_DEC_OSF1 -DOS_NAME=osf1 -DOS_MAJOR_VERSION=3 -DOS_MINOR_VERSION=2 -std $flags $srcfile 2>/dev/null
done
exit 0
